### ISSUE TITLE
可以新创建 project

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/vue3-dida#33]
点击 + 按钮的时候可以新建一个 project
<img width="447" alt="image" src="https://user-images.githubusercontent.com/12064746/211190177-8bcce0b8-f384-42e5-b276-9302899c9a86.png">

点击完成后 显示创建框

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/12064746/211190248-b9f5f78a-fdbf-4bca-b9df-473269a9c33d.png">

<img width="523" alt="image" src="https://user-images.githubusercontent.com/12064746/211190267-b5774521-b011-40e1-a1e3-4873ea65958d.png">

只需要实现可输入project 的 name 以及有两个按钮（关闭、保存）即可

**Comment by xianjianlf2** [comment]
领任务
