### ISSUE TITLE
隐藏智能清单

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/vue3-dida#40]
<img width="388" alt="image" src="https://user-images.githubusercontent.com/12064746/211273564-210f31cc-568b-4246-99e9-b66288b93495.png">

鼠标 hover 到智能清单上后  会显示 右侧的点击按钮   

点击之后显示菜单栏  
点击隐藏后 
该智能清单会被隐藏掉

## 关联的功能
#8

**Comment by xiaoFeng5210** [comment]
I will try
