### ISSUE TITLE
设置面板内的智能清单

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/vue3-dida#55]
## 智能清单
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/12064746/211272742-0ac6a3b9-98a2-479f-bea0-2ce1cf044d15.png">

<img width="534" alt="image" src="https://user-images.githubusercontent.com/12064746/211272807-dc0d8a51-fe6f-4ede-850d-7603e3bc212c.png">

只实现这3个就可以

<img width="536" alt="image" src="https://user-images.githubusercontent.com/12064746/211272864-12768789-bde2-4d34-ba95-989613c5bb8f.png">

<img width="567" alt="image" src="https://user-images.githubusercontent.com/12064746/211272887-3d960568-31fd-45f5-906b-f7b0cbd4f884.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/12064746/211272909-83078adf-d313-4411-9aab-ebcabcb9bc1c.png">

设置完按钮后 会影响主页面 侧边栏智能清单的显示

**Comment by Draculabo** [comment]
领任务

**Comment by zhengbangbo** [comment]
初步完成了这个功能。

但还不支持「有内容时显示」这个选项。

**Comment by cuixiaorui** [comment]
暂时实现了2个   已完成和垃圾桶 现阶段够用了
