### ISSUE TITLE
点击页面右上角主题按钮修改页面主题，设置页的当前主题不同步修改

### ISSUE THREAD

**Issue by RansonZhang** [cuixueshe/vue3-dida#73]
问题描述：
点击页面右上角的主题按钮改主体，设置页的当前主题不会同步更改

![WX20230111-104236@2x](https://user-images.githubusercontent.com/40056125/211706495-b674a243-93c6-43be-a5ee-ead5e855545d.png)

**Comment by zhengbangbo** [comment]
如果只有亮暗两种主题，建议主题设置这里加个「自动」选项。 #8

**Comment by alexzhang1030** [comment]
没复现出来

**Comment by alexzhang1030** [comment]
可以去掉右上角的了，PR welcome
