### ISSUE TITLE
“已放弃“功能和“垃圾箱”功能重叠，建议删除

### ISSUE THREAD

**Issue by xiepengcz** [cuixueshe/vue3-dida#86]
![image](https://user-images.githubusercontent.com/39823619/211806128-a11ebb1f-f3cc-4951-afc7-ca8106ea736d.png)
参考滴答 
![image](https://user-images.githubusercontent.com/39823619/211806348-869b87ee-199a-486e-99aa-e265ee7776a1.png)

**Comment by cuixiaorui** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/12064746/211819970-d05d1bf0-038e-4c3e-a342-cd1b6ffa95fd.png">

就是说  有没有可能你没开启 [旺柴]
