### ISSUE TITLE
bug 点击左侧标签后，输入框输入内容回车会报错

### ISSUE THREAD

**Issue by 1393983569** [cuixueshe/vue3-dida#88]
![865f522bceca85dc8907e9aa6632247](https://user-images.githubusercontent.com/42171813/211852865-3616b493-0cce-4d64-848f-028c858583de.png)

**Comment by Nauxscript** [comment]
标签模块逻辑未完成，等待完成模块后则会正常

**Comment by jobn123** [comment]
从清单内容 点击标签时 右侧的内容应该不发生改变
